### PR TITLE
GO1.14 introducing 

### PR DESCRIPTION
**Pull request by kuritka**
add module verification

add go1.14

upgrade pipeline version to 0.3.0

### CODE REVIEW

**Comment by ytsarev** [comment]
@donovanmuller we agreed with @kuritka that first we e2e test the changes on our fork and pipes. Soon we will send the changes upstream in parallel

**Comment by kuritka** [comment]
Hi @donovanmuller , yes, I wanted  test it first on our *forked* repo and if it goes well I'd like to push it  higher

**Comment by donovanmuller** [comment]
💯

**Comment by kuritka** [comment]
@here Hi finally I sucesfully tested against my [personal fork](https://github.com/kuritka/git-actions/runs/583573479?check_suite_focus=true) and made PR with changes upstream.

regarding release pipe - choukoo gives us compiled executable only. I'm not sure if this is what we expect. Afterwards we can decide what going to be result of release and extend choukoo, create custom pipe,...

**Pull request merged**
